language: objective-c
osx_image: xcode8

before_install:
    - env
    - locale
    - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
    - xcpretty --version
    - xcodebuild -version
    - xcodebuild -showsdks

script:
    - xcodebuild clean build -project LWImporterContainer.xcodeproj -scheme 'LWImporter' -configuration TravisCI | xcpretty -c

after_success:
    - echo Success
